### ISSUE TITLE
NodeJS wrapper - node: symbol lookup error

### ISSUE THREAD

**Issue by stachen** [Picolab/indy-sdk#1]
Hi, 

Thanks for the nodeJS wrapper PR. I'm actually trying it out on ubuntu. However, I'm running into some issue. Is this a known problem or I am just missing something? Detail is as follow:

I did "npm install --save indy-sdk" and ran into a problem when I do the following

```
var indy = require('indy-sdk')

var did = '...'
var fullVerkey = '...'

indy.abbreviateVerkey(did, fullVerkey, function(err, verkey){
  console.log(verkey)
})
```

I get the error message below.

node: symbol lookup error: /home/ubuntudev/test5/node_modules/indy-sdk/build/Release/indynodejs.node: undefined symbol: indy_abbreviate_verkey

Thanks,

**Comment by farskipper** [comment]
Ok, you probably just need the include `libindy.so` in your dynamic lib path.

i.e. `LD_LIBRARY_PATH=/home/ubuntudev/test5 node index.js` (assuming the path is `/home/ubuntudev/test5/libindy.so`)

**Comment by stachen** [comment]
@farskipper Thanks! Much appreciate your response. I somehow got the nodeJS wrapper to build on ubuntu 16.04 now.

Much appreciate your work.
