### ISSUE TITLE
NodeJS: Error during native compile step

### ISSUE THREAD

**Issue by alexvoro** [Picolab/indy-sdk#3]
Hi,

Thank you for making the nodejs wrapper. I wanted to try it out on a mac and ran into some build issues. Is there something missing in the setup, or could you recommend the build steps?

After running:
`LD_LIBRARY_PATH=../../indy-sdk/libindy/target/debug npm i --save indy-sdk`

Getting error on `node-gyp rebuild:
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/indynodejs/src/indy.o
> ../src/indy.cc:185:34: error: variable length array of non-POD element type 'v8::Local<v8::Value>'
>         v8::Local<v8::Value> argv[argc];
> 

Also I've tried cloning and rebuilding the repo, with "npm run-script rebuild"  and getting the same error locally.
The contents of the /indy.cc:185:34 are in the screenshot attached
<img width="400" alt="screen shot 2018-04-30 at 13 56 27" src="https://user-images.githubusercontent.com/5556760/39426832-aaf0dde2-4c81-11e8-8147-da2159242ce1.png">

Thank you!

**Comment by farskipper** [comment]
Ok, looks like you are trying the right things. What version of node are you using? `node -v`

**Comment by farskipper** [comment]
@alexvoro  Just made a fix and pushed it. Also published `indy-sdk@0.2.4`

Let me know how it goes.

**Comment by alexvoro** [comment]
@farskipper The fix in + indy-sdk@0.2.4 worked, thanks lots.
