### ISSUE TITLE
for issuerCreateCredential, if blob_storage_reader_handle is null it should be set to -1

### ISSUE THREAD

**Issue by saholman** [Picolab/indy-sdk#4]
Since the blob_storage_reader_handle is an optional parameter, if it is null it needs to be set to -1 before being passed to indy.

**Comment by saholman** [comment]
Also, when -1 is passed in directly it results in a SEGFAULT.

**Comment by farskipper** [comment]
Just published `indy-sdk@0.2.5` that should fix both of these issues.
